version: '3.8'

services:
  app:
    build: .
    ports:
      - '3002:3001'
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=dbadmin
      - DB_PASSWORD=dbadmin1793
      - DB_NAME=fibonacci_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-here
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: dbadmin1793
      MYSQL_DATABASE: fibonacci_db
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: dbadmin1793
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: dbadmin
      PMA_PASSWORD: dbadmin1793
      PMA_ARBITRARY: 1
    ports:
      - '8080:80'
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
